name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        working-directory: repo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Train model
        working-directory: repo
        run: python train.py
        
      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Clone the specific Hugging Face Space repository
          git clone https://$HF_TOKEN@huggingface.co/spaces/zubayr-ahmad-hugging-face/titanic-app huggingface-space
          
          # Copy files from our repository to the Hugging Face Space directory
          cp -r repo/* huggingface-space/
          
          # Navigate to the Hugging Face Space directory
          cd huggingface-space
          
          # Add, commit, and push changes
          git add .
          git commit -m "Update from GitHub Actions"
          git push https://$HF_TOKEN@huggingface.co/spaces/zubayr-ahmad-hugging-face/titanic-app main
